# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Random Thoughts
email: contact@yunhocho.com
description: >- # this means to ignore newlines until "baseurl:"
  세련되지 못하고, 오글거릴지라도, 진실과 진심을 담은 생각들 |
  raw, unfiltered, cringeworthy, but truthful thoughts
# idea: iterate between whatever, whichever, however, wherever based on random refreshes or every 2 seconds w/ animation!
# idea: alternate between fuck's, hell's, crap's, shit's,
baseurl: "/" # the subpath of your site, e. g. /blog
url: "https://random-thoughts.yunhocho.com" # the base hostname & protocol for your site, e.g. http://example.com
icon: /assets/images/icon-512.png
twitter_username: yhjc2692
github_username:  k2m5t2

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/page/:num/"
